language: go

go:
  - 1.6
  - 1.7
  - 1.8

env:
 - GOMAXPROCS=4

before_install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -v -covermode=count -coverprofile=cover.out --tags=integration ./...

after_success:
  - $HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=cover.out
